name: CI

on: [push, pull_request]

jobs:
  build:
    name: Create distribution files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Build files
        run: |
          python -m pip install build
          pyproject-build
      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: b2h5py-dist
          path: |
            dist/b2h5py-*.tar.gz
            dist/b2h5py-*.whl
  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Download files
        uses: actions/download-artifact@v3
        with:
          name: b2h5py-dist
      - name: Install
        run: |
          python -m pip install b2h5py-*.whl
      - name: Test
        run: |
          python -m unittest discover b2h5py.tests

  h5py-test:
    name: Run patched h5py tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Download files
        uses: actions/download-artifact@v3
        with:
          name: b2h5py-dist
      - name: Install
        run: |
          python -m pip install $(echo b2h5py-*.whl)[h5py-test]
      - name: Test
        run: |
          python -m b2h5py.tests.test_patched_h5py
